version: 2.1

orbs:
  node-orb: heug/node@dev:0.0.2

jobs:
  build:
    executor:
      name: node-orb/node # put executor in the name
      tag: "6"
    steps:
      - checkout
      - node-orb/install_package_manager:
          npm: true
          yarn: true
      - node-orb/with_cache:
          steps:
            - run: 
                command: npm install
      - run: mkdir ~/project/junit
      - run:
          command: npm test
          environment:
            MOCHA_FILE: ~/project/junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/project/junit
      - store_artifacts:
          path: ~/project/junit

workflows:
  build-test-deploy:
    jobs:
      - build